### https://quay.io/repository/debezium/server?tab=tags
services:
  debezium-server:
    image: quay.io/debezium/server:3.6.0.Final
    container_name: debezium-server
    restart: unless-stopped
    ports:
      - "8199:8080"
    volumes:
      - /application/docker/debezium/application.properties:/debezium/config/application.properties:z
      - /application/volumes/debezium/data:/debezium/data:z
    environment:
      - QUARKUS_LOG_CONSOLE_FORMAT=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n
      - QUARKUS_LOG_CONSOLE_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
